### PR TITLE
telink: b92: tlsr9268j: update ble lib.

### PR DESCRIPTION
**Pull request by fengtai-telink**
update 2/3/3.5MB flash protection for TLSR9268J .

### CODE REVIEW

**Comment by fengtai-telink** [comment]
Hi andriy, we need to update the ble lib to enable TLSR9268J to support flash protection. Can you please help me merge it in?

**Comment by haiwentelink** [comment]
Hi andriy , this lib is used noly for the cutomer which will use the chip of the tlsr9268j , and the efuse will not the same as the common version , we want to keep the lib in the master branch which seems have no difference with common version .

**Comment by andy-liu-telink** [comment]
@andriy-bilynskyy 
We will introduce a new method to integrate this library file.

**Comment by fengtai-telink** [comment]
As andy said, we have a new lib release method, so this PR will be closed.

**Pull request closed without merging**
