### PR TITLE
telink:b95: update ble lib

### PR DESCRIPTION
**Pull request by haiwentelink**
- update the ble lib to the version of 5d51c37b8f8636ce3a98963b3e6929b950865b35.
- fix the rf switch func in the lib.

### CODE REVIEW

**Comment by haiwentelink** [comment]
update the lib, will use the PR to pass temporary to pass the zephyr CI part .

**Review by s07641069 — APPROVED** [review]

**Comment by andriy-bilynskyy** [comment]
PR seems fine. But plese squash your commits. There is no any reasons to keep middle library version.

**Comment by haiwentelink** [comment]
will merge into one .

**Comment by haiwentelink** [comment]
done

**Review by s07641069 — APPROVED** [review]

**Pull request merged**
